project:
  type: website

website:
  title: "feral lab"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - sidebar:research
      - sidebar:about
      - href: recruit.qmd
        text: "Opportunities"
  sidebar: 
      - id: about
        title: "Who We Are"
        contents: 
        - text: "People"
          href: people.qmd
        - text: "Contact"
          href: contact.qmd
      - id: research
        title: "What We Do"
        contents:
        - text: "Research"
          href: research.qmd
        - text: "Publications"
          href: publications.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

